const mongoose = require('mongoose');

const claimItemSchema = new mongoose.Schema({
  batchId: { type: String, required: true, index: true },
  maLK: { type: String, trim: true },
  maCSKCB: { type: String, trim: true },
  xmlType: { type: String, trim: true },
  maBN: { type: String, trim: true },
  hoTen: { type: String, trim: true },
  ngaySinh: { type: Date },
  soCCCD: { type: String, trim: true },
  soNgayDieuTri: { type: Number },
  ngayVao: { type: Date },
  ngayRa: { type: Date },
  ngayVaoNoiTru: { type: Date },
  ketQuaDieuTri: { type: String, trim: true },
  maLoaiRaVien: { type: String, trim: true },
  loaiKCB: { type: String, trim: true },
  maDoiTuongKCB: { type: String, trim: true },
  maThe: { type: String, trim: true },
  maDkbd: { type: String, trim: true },
  giayChuyenTuyen: { type: String, trim: true },
  lyDoVv: { type: String, trim: true },
  maKhoa: { type: String, trim: true },
  maBacSi: { type: String, trim: true },
  maGiuong: { type: String, trim: true },
  maNhom: { type: String, trim: true },
  mucHuong: { type: Number },
  tyLeTtBh: { type: Number },
  loaiChiPhi: { type: String, trim: true },
  maChiPhi: { type: String, required: true, trim: true },
  tenChiPhi: { type: String, trim: true },
  soDangKy: { type: String, trim: true },
  ttThau: { type: String, trim: true },
  donViTinh: { type: String, trim: true },
  duongDung: { type: String, trim: true },
  hamLuong: { type: String, trim: true },
  soLuong: { type: Number },
  donGia: { type: Number },
  deNghi: { type: Number },
  giamTru: { type: Number },
  ngayYLenh: { type: Date },
  ngayTT: { type: Date },
  lyDoTuChoi: { type: String, trim: true },
  loaiGiamTru: { type: String, trim: true },
  sttXML: { type: String, trim: true },
  sourceSheet: { type: String, trim: true },
  createdAt: { type: Date, default: Date.now },
});

claimItemSchema.index({ batchId: 1, maChiPhi: 1 });

module.exports = mongoose.model('ClaimItem', claimItemSchema);
